##placeholders
##player displayname: %player%
first-join-message: "&b&l%player%&r &bHas Joined for the first time!"
join-message: "&b&l%player%&r &bHas Joined, welcome back"
leave-message: "&b&l%player%&r &bHas Lefted"
##teleport bow plugin messages
give-on-join: true
bow-name: '&f[&eTeleport&aBow&f]'
bow-descryption: '&6 Shoot and teleport anywhere'
teleport-message: '&aSwoosh!'